#!/bin/sh
#
# Copyright (c) 2016 Lawrence King lawrencek52@gmail.com
# All Rights Reserved
#

scratch ~/breakerball_scratch/breakerball.sb &
sleep 15
sudo python ~/breakerball_sensor/slider_sensor.py
